site_name: BenchBBoxTest
site_description: A Python package for benchmarking black-box testing methods
repo_url: https://github.com/jiantingfeng/BenchBBoxTest
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [benchbboxtest]
          options:
            docstring_style: google
            show_source: true
            show_category_heading: true
            show_root_heading: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Installation: user-guide/installation.md
    - Examples: user-guide/examples.md
  - API Reference:
    - Core: api/core.md
    - Datasets:
      - Text: api/datasets/text.md
      - Image: api/datasets/image.md
      - Simulation: api/datasets/simulation.md
    - Evaluation: api/evaluation.md
    - Utils: api/utils.md
  - Contributing: contributing.md 